### ISSUE TITLE
Setup Help

### ISSUE THREAD

**Issue by ralpheeee88** [pimutils/vdirsyncer#659] opened 2017-08-05 08:55 UTC
vdirsyncer, version 0.16.0
Arch
config: http://ix.io/yTe
error: http://ix.io/yUj

been trying to sync  and keep getting credential error's. I also tried another storage provider and got the same error. Any pointers would be greatly appreciated. Thxs!

Before you submit bug reports: https://vdirsyncer.pimutils.org/en/stable/contributing.html

Things to include in your bugreport:

* Your vdirsyncer version
* If applicable, which server software (and which version) you're using
* Your Python version
* Your operating system
* Your config file
* Use `vdirsyncer -vdebug` for debug output. The output is sensitive, but
  please attach at least the last few lines before the error (if applicable),
  censored as necessary. This is almost always the most useful information.

**Comment by untitaker** [comment] 2017-08-05 09:17
As said I don't know what the issue is, so I'm not sure what to reply here.

**Comment by untitaker** [comment] 2017-08-05 09:49
(closing as discussed in IRC)

**Closed by untitaker** 2017-08-05 09:49 UTC
Labels: type: question
