### ISSUE TITLE
Random cannot import name 'metasync' with python3.9

### ISSUE THREAD

**Issue by Kivou-2000607** [pimutils/vdirsyncer#862] opened 2021-01-11 21:41 UTC
Before you submit bug reports: https://vdirsyncer.pimutils.org/en/stable/contributing.html

Things to include in your bugreport:

* Your vdirsyncer version 0.16.9.dev0+gb5dd092.d20201113
* If applicable, which server software (and which version) you're using: n/a
* Your Python version 3.9.1
* Your operating system Manjaro Linux
* Your config file n/a
* Use `vdirsyncer -vdebug` for debug output. The output is sensitive, but
  please attach at least the last few lines before the error (if applicable),
  censored as necessary. This is almost always the most useful information.

```
> vdirsyncer -vdebug metasync       
debug: Using 1 maximal workers.
error: Unknown error occurred: cannot import name 'metasync' from partially initialized module 'vdirsyncer.metasync' (most likely due to a circular import) (/usr/lib/python3.9/site-packages/vdirsyncer/metasync.py)
error: Use `-vdebug` to see the full traceback.
debug:   File "/usr/lib/python3.9/site-packages/vdirsyncer/cli/utils.py", line 339, in _worker
debug:     func(wq=self)
debug:   File "/usr/lib/python3.9/site-packages/vdirsyncer/cli/tasks.py", line 119, in metasync_collection
debug:     from ..metasync import metasync
```

* It seems to be close to #583 
* Lowering the number of workers seems to lower the probability of the error showing up. But even with `--max-workers=1` it pops up from time to time.
* I've tried with the python from the system and from a virtual env but it gives the same error.
* I never had an issue with python3.8

**Comment by solonovamax** [comment] 2021-01-24 20:27
Along with what the other people said in the other issue,
It definitely seems to have something to do with the magic number 2.

If I run with (for example) 4 workers (`vdirsyncer -vdebug metasync --max-workers=4`), then exactly 2 tasks to different calendars will be successful. So if I had the remote calendars `a`, `b`, `c`, and `d` and used 4 workers, then, for example, the tasks for calendars `a` and `b` would fail but `c` and `d` will succeed. This scales up to the 8 calendars I have on my nextcloud server when I encountered this. It seems what is happening is that two workers will succeed in the import, and then if you have any more than 2 workers, only those additional workers will fail. If you only had 1 additional worker (so 3 in total), then that 1 extra worker will fail for the first task, instantly load up the next task and fail for that one too. It then continues loading the next task until there are no remaining tasks in the queue, which is why it's always 2 tasks that pass and the rest fail.

Also, it seems to be some form of race condition.
My reason for believing this is that randomly one time I had a task with 3 workers pass successfully.
I don't know _why_ it was successful. It is also reproducible. Just keep running `vdirsyncer -vdebug metasync --max-workers=3`, and cancelling it if it fails.
I believe this may be because for some reason there's some static initialization (???) that needs to happen in the `metasync` module before it can be properly imported. (I looked at the `metasync.py` file, and I don't know either... I don't see *why* it would do this, but it *does* do this. Unless I'm completely misunderstanding what's happening here. But I'm pretty sure it's a race condition. Either that or black magic.)

Additionally, it seems that if you increase the workers sufficiently, then you will have _less_ than 2 tasks that succeed. (So maybe it's just random chance that generally 2 workers take long enough to pass the import? Who knows.) So if I use 8 workers for my 8 calendars, generally only 1 will succeed. (This is not always true though. For example, I ran a metasync with 20 workers, where only 2 out of 8 failed. There was probably something that slowed down the initialization of those workers.) If I increase it all the way up to 99 workers (why...), then there's a possibility that *none* of the tasks finish successfully.

So, what I believe would be a good solution would be the following:
Whenever vdirsyncer is about to begin a metasync task, it first spawns a worker thread. That worker thread just imports the `metasync` module in a loop, which continues if it catches an error and exits if it imports successfully. That way, the module will be fully initialized by the time the workers start. (I think that's how python works. idk man)
The main program then just waits for this worker to finish execution before spawning & running the other workers.
I can't test if this would work because I'm a java programmer and don't have much experience with python (and you probably wouldn't want my shit code anyway), but I believe that this _should_ solve the problem, given what I've seen it do so far.
It does seem kinda hacky, it would _work_. Yeah, I hate to do hacks and workarounds like this, but doing that is probably better than just having a sleep call in all the threads.

Anyways, that was a pretty long comment. Hopefully, I didn't bore anyone to death with it.

**Comment by dessert1** [comment] 2021-03-18 10:49
I get the same error on Arch Linux with vdirsyncer v0.16.9.dev0+gb5dd092.d20210202, python v3.9.2 and only one calendar. In my case `metasync` works reliably only with `max-workers=1`, with apparently any value >1 around 85 % of the calls fail:
```bash
+$ k=0; for i in {1..100}; do vdirsyncer metasync --max-workers=1 &>/dev/null || ((k++)); done; printf 'failed: %03d/100d\n' $k
failed: 000/100
+$ k=0; for i in {1..100}; do vdirsyncer metasync --max-workers=2 &>/dev/null || ((k++)); done; printf 'failed: %03d/100d\n' $k
failed: 085/100
failed: 083/100  # second run
+$ k=0; for i in {1..100}; do vdirsyncer metasync --max-workers=99 &>/dev/null || ((k++)); done; printf 'failed: %03d/100d\n' $k
failed: 088/100
failed: 087/100  # second run

**Comment by WhyNotHugo** [comment] 2021-06-14 11:33
I can't reproduce this on 0.18.0. Can you confirm it's fixed for you too?

**Comment by WhyNotHugo** [comment] 2021-07-14 18:56
Closing, since this seems to be fixed. Please let me know if it isn't.

**Closed by WhyNotHugo** 2021-07-14 18:56 UTC
