### ISSUE TITLE
CANCELLED status seems to fail syncing to Google Calendar

### ISSUE THREAD

**Issue by waynew** [pimutils/vdirsyncer#510] opened 2016-09-28 15:39 UTC
- Your vdirsyncer version: `0.12.1`
- Your Python version: `3.5.2`
- Your operating system: Arch Linux
- Your config file:
  
  ```
  [general]
  status_path = ~/.config/vdirsyncer/status
  
  
  [pair google_calendar]
  a = google_calendar_remote
  b = google_calendar_local
  collections = ["me@gmail.com"]
  conflict_resolution = "b wins"
  
  [storage google_calendar_remote]
  type = google_calendar
  client_id = "notreallymyid.apps.googleusercontent.com"
  client_secret = "really_real_secret"
  token_file = /path/to/my/tokens
  
  [storage google_calendar_local]
  type = filesystem
  path = /path/to/my/calendar
  fileext = .ics
  ```
- debug output:

```
debug:   File "/home/wayne/.local/lib/python3.5/site-packages/vdirsyncer/cli/tasks.py", line 66, in sync_collection
debug:     force_delete=force_delete
debug:   File "/home/wayne/.local/lib/python3.5/site-packages/vdirsyncer/sync.py", line 228, in sync
debug:     action(a_info, b_info, conflict_resolution)
debug:   File "/home/wayne/.local/lib/python3.5/site-packages/vdirsyncer/sync.py", line 248, in inner
debug:     dest_href, dest_etag = dest.storage.upload(item)
debug:   File "/home/wayne/.local/lib/python3.5/site-packages/vdirsyncer/storage/base.py", line 17, in inner
debug:     return f(self, *args, **kwargs)
debug:   File "/home/wayne/.local/lib/python3.5/site-packages/vdirsyncer/storage/base.py", line 17, in inner
debug:     return f(self, *args, **kwargs)
debug:   File "/home/wayne/.local/lib/python3.5/site-packages/vdirsyncer/storage/base.py", line 17, in inner
debug:     return f(self, *args, **kwargs)
debug:   File "/home/wayne/.local/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 503, in upload
debug:     return self._put(href, item, None)
debug:   File "/home/wayne/.local/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 474, in _put
debug:     headers=headers
debug:   File "/home/wayne/.local/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 333, in request
debug:     return utils.http.request(method, url, session=self._session, **more)
debug:   File "/home/wayne/.local/lib/python3.5/site-packages/vdirsyncer/utils/http.py", line 72, in request
debug:     raise exceptions.NotFoundError(r.reason)

```

You can probably reproduce this issue yourself. First, make sure that your Google calendar has been synced with `vdirsyncer sync`. Then, with Google calendar go create an appointment - any old appointment will do. Re-run `vdirsyncer sync` again and you should see an appointment being synced. Open this file with your favorite editor and find the line that says

```
STATUS:CONFIRMED
```

And change it to

```
STATUS:CANCELLED
```

In [section 4.8.1.11](https://www.ietf.org/rfc/rfc2445.txt) it says:

```
   Format Definition: The property is defined by the following notation:

     status     = "STATUS" statparam] ":" statvalue CRLF

     statparam  = *(";" xparam)

     statvalue  = "TENTATIVE"           ;Indicates event is
                                        ;tentative.
                / "CONFIRMED"           ;Indicates event is
                                        ;definite.
                / "CANCELLED"           ;Indicates event was
                                        ;cancelled.
        ;Status values for a "VEVENT"
```

However, when one does `vdirsyncer sync` after this it produces the above error.

I'm not 100% sure what the expected behavior here would be. For a one-time event I'm pretty sure that it should be deleted, but I'm not sure about a recurring event. For instance, we have a standing appointment every week, but this week it was cancelled. Only the one occurrence, though.

**Comment by untitaker** [comment] 2016-09-28 17:30
I'm unsure what vdirsyncer is supposed to do here either. ISTM that the best way to deal with this is to report this against Google but I strongly doubt that they'll listen.

**Comment by waynew** [comment] 2016-09-28 19:56
Is this a matter of the event actually not being found? I'm very unfamiliar with what vdirsyncer is actually trying to attempt against the Google API

**Comment by untitaker** [comment] 2016-09-28 19:57
This just appears to be Google's way of rejecting the item upload.

On 28 September 2016 21:56:09 CEST, Wayne Werner <notifications@github.com> wrote:
>Is this a matter of the event actually not being found? I'm very
>unfamiliar with what vdirsyncer is actually trying to attempt against
>the Google API
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/510#issuecomment-250281256

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment] 2017-02-02 15:04
I'm closing this since it's not a bug in vdirsyncer, but perhaps an intentional restriction at Google's side.

**Closed by untitaker** 2017-02-02 15:04 UTC
Labels: mod: Google, server compat
