### ISSUE TITLE
Vdirsyncer crashes on google contacts sync

### ISSUE THREAD

**Issue by m-wynn** [pimutils/vdirsyncer#523] opened 2016-11-19 01:56 UTC
Vdirsyncer is crashing when attempting to discover google contacts.

* vdirsyncer 0.14.0
* Python 3.5.2
* Void Linux
* [Config File](http://hastebin.com/palofanoqi.ini)
* [Output](http://hastebin.com/odomibenaj.lua) of `vdirsyncer -vdebug discover google_contacts`

**Comment by untitaker** [comment] 2016-11-20 01:59
So I fixed this particular crash in https://github.com/pimutils/vdirsyncer/commit/e08d096f29502cf5eef3bd6a35807d38e6d7df29, but I don't really think that'll help you.

**Comment by untitaker** [comment] 2017-01-05 17:04
@m-wynn could you try again?

**Comment by m-wynn** [comment] 2017-01-05 17:45
Looks like it got a little further this time.

[Output](https://hastebin.com/comaxonuke.lua) of vdirsyncer -vdebug discover google_contacts

Config file and environment are the same.  This is vdirsyncer 0.14.1.

**Comment by untitaker** [comment] 2017-01-05 18:06
Oh no that's technically entirely the same. The response is the same, and I have no idea what causes it. I can't reproduce it, even with intentionally faulty configuration of the OAuth credentials and the like.

**Comment by m-wynn** [comment] 2017-01-05 18:34
Could it be something to do with Google Apps vs a standard Google account

**Comment by untitaker** [comment] 2017-01-05 18:43
I'm not familiar with Google products. What is the difference?

On 5 January 2017 19:34:49 CET, Matthew Wynn <notifications@github.com> wrote:
>Could it be something to do with Google Apps vs a standard Google
>account
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/523#issuecomment-270720279

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by m-wynn** [comment] 2017-01-05 20:49
G Suite is an alternative to the standard Google account, primarily aimed at businesses.  It used to be free, but new accounts are paid now.  It allows you to have your own domain name for your email, instead of username@gmail.com.  It has slightly stricter security policies by default, a complicated control panel for admins to control what their users have access to (I checked and everything looks to be allowed), and some services are disabled by default (or don't exist at all!)  It's not likely the issue, but it's possible.

The only other thing I can think of would be that I'm only syncing contacts, and not calendar?

**Comment by untitaker** [comment] 2017-01-05 20:53
That sounds vastly different from what vdirsyncer's google support was built to support. Does google contacts work at the same exact URL as the free version? Have you had success with Google Calendar?

**Comment by untitaker** [comment] 2017-02-28 17:56
I'm closing this because a lot of things regarding Google Contacts have been fixed, most recently #564. If this issue persists, please reopen.

**Closed by untitaker** 2017-02-28 17:56 UTC
Labels: 3rd party, mod: Google, type: question
